import { useEffect, useState } from "react";
import { api } from "../services/api";
const categories = ["Pizza Bases", "Sauces", "Cheeses", "Vegetables"];

export default function Admin() {
  const [token, setToken] = useState(localStorage.getItem("adminToken"));
  const [credentials, setCredentials] = useState({ email: "", password: "" });
  const [item, setItem] = useState({ name: "", category: categories[0], quantity: 0, threshold: 10 });
  const [data, setData] = useState(null); const [error, setError] = useState("");
  const load = async () => { try { const [dashboard, orders, inventory] = await Promise.all([api("/admin/dashboard", { token }), api("/admin/orders", { token }), api("/admin/inventory", { token })]); setData({ dashboard, orders, inventory }); setError(""); } catch (e) { setError(e.message); } };
  useEffect(() => { if (token) load(); }, [token]);
  const login = async e => { e.preventDefault(); try { const result = await api("/admin/login", { method: "POST", body: JSON.stringify(credentials) }); localStorage.setItem("adminToken", result.token); setToken(result.token); } catch (e) { setError(e.message); } };
  const changeStatus = async (id, orderStatus) => { try { await api(`/admin/orders/${id}/status`, { method: "PATCH", token, body: JSON.stringify({ orderStatus }) }); load(); } catch (e) { setError(e.message); } };
  const addItem = async e => { e.preventDefault(); try { await api("/admin/inventory", { method: "POST", token, body: JSON.stringify({ ...item, quantity: Number(item.quantity), threshold: Number(item.threshold) }) }); setItem({ name: "", category: categories[0], quantity: 0, threshold: 10 }); load(); } catch (e) { setError(e.message); } };
  const adjust = async (stock, direction) => { const quantity = Math.max(0, stock.quantity + direction); try { await api(`/admin/inventory/${stock._id}`, { method: "PATCH", token, body: JSON.stringify({ quantity }) }); load(); } catch (e) { setError(e.message); } };
  if (!token) return <div className="auth-page"><div className="auth-card"><div className="auth-logo">🍕</div><h1>Admin sign in</h1><form onSubmit={login}><label>Email</label><input type="email" required onChange={e => setCredentials({ ...credentials, email: e.target.value })}/><label>Password</label><input type="password" required onChange={e => setCredentials({ ...credentials, password: e.target.value })}/><button className="primary-btn">Sign in</button></form>{error && <p className="form-error">{error}</p>}</div></div>;
  if (!data) return <main className="dashboard">Loading admin dashboard…</main>;
  return <main className="dashboard"><div className="dashboard-top"><div><span>ADMIN</span><h1>PizzaCraft operations</h1></div><button className="secondary-btn" onClick={() => { localStorage.removeItem("adminToken"); setToken(null); }}>Logout</button></div>{error && <p className="form-error">{error}</p>}<div className="stats-grid">{[["Total orders", data.dashboard.total], ["Pending", data.dashboard.pending], ["In kitchen", data.dashboard.kitchen], ["Out for delivery", data.dashboard.delivery], ["Users", data.dashboard.users], ["Low stock", data.dashboard.lowStock.length]].map(([label, value]) => <div className="dashboard-card" key={label}><span>{label}</span><h2>{value}</h2></div>)}</div><h2>Order management</h2><div className="orders-list">{data.orders.map(order => <article className="order-card" key={order._id}><div><strong>#{order._id.slice(-6).toUpperCase()}</strong><p>{order.user?.name} · ₹{order.totalAmount} · {order.paymentStatus}</p></div><select value={order.orderStatus} onChange={e => changeStatus(order._id, e.target.value)}>{["Order Received", "In Kitchen", "Sent to Delivery"].map(status => <option key={status}>{status}</option>)}</select></article>)}</div><h2>Inventory</h2><form className="inventory-form" onSubmit={addItem}><input placeholder="Ingredient name" required value={item.name} onChange={e => setItem({ ...item, name: e.target.value })}/><select value={item.category} onChange={e => setItem({ ...item, category: e.target.value })}>{categories.map(category => <option key={category}>{category}</option>)}</select><input type="number" min="0" value={item.quantity} onChange={e => setItem({ ...item, quantity: e.target.value })}/><input type="number" min="0" value={item.threshold} onChange={e => setItem({ ...item, threshold: e.target.value })}/><button className="primary-btn">Add stock item</button></form><div className="orders-list">{data.inventory.map(stock => <article className="order-card" key={stock._id}><div><strong>{stock.name}</strong><p>{stock.category} · alert at {stock.threshold}</p></div><div className="stock-controls"><button onClick={() => adjust(stock, -1)} className="secondary-btn">−</button><b>{stock.quantity}</b><button onClick={() => adjust(stock, 1)} className="secondary-btn">+</button></div></article>)}</div></main>;
}
