const Admin=require("../models/Admin"), User=require("../models/User"), Order=require("../models/Order"), Inventory=require("../models/Inventory"), bcrypt=require("bcryptjs"), jwt=require("jsonwebtoken");
const login=async(req,res,next)=>{try{const admin=await Admin.findOne({email:req.body.email?.toLowerCase()});if(!admin||!(await bcrypt.compare(req.body.password||"",admin.password)))return res.status(401).json({message:"Invalid admin credentials"});const token=jwt.sign({id:admin._id,role:"admin"},process.env.JWT_SECRET,{expiresIn:"1d"});res.json({token,admin:{name:admin.name,email:admin.email}});}catch(e){next(e);}};
const dashboard=async(req,res,next)=>{try{const [total,pending,kitchen,delivery,users,lowStock]=await Promise.all([Order.countDocuments(),Order.countDocuments({orderStatus:"Order Received"}),Order.countDocuments({orderStatus:"In Kitchen"}),Order.countDocuments({orderStatus:"Sent to Delivery"}),User.countDocuments(),Inventory.find({$expr:{$lt:["$quantity","$threshold"]}})]);res.json({total,pending,kitchen,delivery,users,lowStock});}catch(e){next(e);}};
const orders=async(req,res,next)=>{try{res.json(await Order.find().populate("user","name email").sort({createdAt:-1}));}catch(e){next(e);}};
const changeStatus=async(req,res,next)=>{try{if(!["Order Received","In Kitchen","Sent to Delivery"].includes(req.body.orderStatus))return res.status(400).json({message:"Invalid order status"});const order=await Order.findByIdAndUpdate(req.params.id,{orderStatus:req.body.orderStatus},{new:true});if(!order)return res.status(404).json({message:"Order not found"});req.app.get("io")?.to(`user:${order.user}`).emit("order:updated",order);res.json({order});}catch(e){next(e);}};
const inventory=async(req,res,next)=>{try{res.json(await Inventory.find().sort({category:1,name:1}));}catch(e){next(e);}};
const addInventory=async(req,res,next)=>{try{const {name,category,quantity,threshold}=req.body;if(!name||!category||quantity==null)return res.status(400).json({message:"Name, category and quantity are required"});res.status(201).json({item:await Inventory.create({name,category,quantity,threshold})});}catch(e){next(e);}};
const updateInventory=async(req,res,next)=>{try{const item=await Inventory.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!item)return res.status(404).json({message:"Inventory item not found"});res.json({item});}catch(e){next(e);}};
module.exports={login,dashboard,orders,changeStatus,inventory,addInventory,updateInventory};
